tap "homebrew/cask-fonts"
tap "thoughtbot/formulae"
tap "mongodb/brew"
tap "hazcod/homebrew-hazcod"

brew "p7zip"
brew "ffmpeg"
brew "yarn"
brew "zsh"
brew "z"
brew "rcm"
brew "mas"
brew "screenfetch"

cask "transmission"
cask "font-fira-code"