tap "homebrew/cask-fonts"
tap "thoughtbot/formulae"
brew tap "mongodb/brew"

brew "p7zip"
brew "ffmpeg"
brew "gitup"
brew "node"
brew "yarn"
brew "zsh"
brew "z"
brew "rcm"
brew "mas"
brew "screenfetch"
brew "mongodb-community@4.0"
brew "neovim"
brew "watson"

cask "transmission"
cask "visual-studio-code"
cask "appcleaner"
cask "processing"
cask "spotify"
cask "iina"
cask "font-fira-code"
cask "wwdc"
cask "energybar"
cask "kawa"
