brew "autoconf"
brew "automake"
brew "git-lfs"
brew "gmp"
brew "libgpg-error"
brew "libksba"
brew "libtool"
brew "libyaml"
brew "node"
brew "openssl"
brew "p7zip"
brew "pkg-config"
brew "rbenv"
brew "readline"
brew "ruby-build"
brew "wget"
brew "z"
tap "thoughtbot/formulae"
brew "rcm"

brew cask install "appcleaner"
brew cask install "coda"
brew cask install "handbrakecli"
brew cask install "hyper"
brew cask install "iterm2"
brew cask install "mactracker"
brew cask install "sourcetree"
brew cask install "xquartz"
